export const LOGIN = 'LOGIN';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

export const PROFILE = 'PROFILE';
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const KNOWLEDGE = 'KNOWLEDGE';
export const GET_KNOWLEDGE_REQUEST = 'GET_KNOWLEDGE_REQUEST';
export const GET_KNOWLEDGE_SUCCESS = 'GET_KNOWLEDGE_SUCCESS';
export const GET_KNOWLEDGE_ERROR = 'GET_KNOWLEDGE_ERROR';

export const STRUCTURED = 'STRUCTURED';
export const GET_STRUCTURED_REQUEST = 'GET_STRUCTURED_REQUEST';
export const GET_STRUCTURED_SUCCESS = 'GET_STRUCTURED_SUCCESS';
export const GET_STRUCTURED_ERROR = 'GET_STRUCTURED_ERROR';

export const REGULATION = 'REGULATION';
export const GET_REGULATION_REQUEST = 'GET_REGULATION_REQUEST';
export const GET_REGULATION_SUCCESS = 'GET_REGULATION_SUCCESS';
export const GET_REGULATION_ERROR = 'GET_REGULATION_ERROR';

export const RAW = 'RAW';
export const GET_RAW_REQUEST = 'GET_RAW_REQUEST';
export const GET_RAW_SUCCESS = 'GET_RAW_SUCCESS';
export const GET_RAW_ERROR = 'GET_RAW_ERROR';

export const GROUP = 'GROUP';
export const GET_GROUP_REQUEST = 'GET_GROUP_REQUEST';
export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS';
export const GET_GROUP_ERROR = 'GET_GROUP_ERROR';

export const DATASET = 'DATASET';
export const GET_DATASET_REQUEST = 'GET_DATASET_REQUEST';
export const GET_DATASET_SUCCESS = 'GET_DATASET_SUCCESS';
export const GET_DATASET_ERROR = 'GET_DATASET_ERROR';

export const CYCLEDETAILS = 'CYCLEDETAILS';
export const GET_CYCLEDETAILS_REQUEST = 'GET_CYCLEDETAILS_REQUEST';
export const GET_CYCLEDETAILS_SUCCESS = 'GET_CYCLEDETAILS_SUCCESS';
export const GET_CYCLEDETAILS_ERROR = 'GET_CYCLEDETAILS_ERROR';

export const SPECIFIC_CYCLEDETAIL = 'SPECIFIC_CYCLEDETAIL';
export const GET_SPECIFIC_CYCLEDETAIL_REQUEST = 'GET_SPECIFIC_CYCLEDETAIL_REQUEST';
export const GET_SPECIFIC_CYCLEDETAIL_SUCCESS = 'GET_SPECIFIC_CYCLEDETAIL_SUCCESS';
export const GET_SPECIFIC_CYCLEDETAIL_ERROR = 'GET_SPECIFIC_CYCLEDETAIL_ERROR';

export const SPECIFIC_GROUP = 'SPECIFIC_GROUP';
export const GET_SPECIFIC_GROUP_REQUEST = 'GET_SPECIFIC_GROUP_REQUEST';
export const GET_SPECIFIC_GROUP_SUCCESS = 'GET_SPECIFIC_GROUP_SUCCESS';
export const GET_SPECIFIC_GROUP_ERROR = 'GET_SPECIFIC_GROUP_ERROR';

export const CONTENT = 'CONTENT';
export const GET_CONTENT_REQUEST = 'GET_CONTENT_REQUEST';
export const GET_CONTENT_SUCCESS = 'GET_CONTENT_SUCCESS';
export const GET_CONTENT_ERROR = 'GET_CONTENT_ERROR';

export const CYCLES = 'CYCLES';
export const GET_CYCLES_REQUEST = 'GET_CYCLES_REQUEST';
export const GET_CYCLES_SUCCESS = 'GET_CYCLES_SUCCESS';
export const GET_CYCLES_ERROR = 'GET_CYCLES_ERROR';

export const CONTACT = 'CONTACT';
export const GET_CONTACT_REQUEST = 'GET_CONTACT_REQUEST';
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS';
export const GET_CONTACT_ERROR = 'GET_CONTACT_ERROR';

export const KNOWLEDGE_DETAILS = 'KNOWLEDGE_DETAILS';
export const GET_KNOWLEDGE_DETAILS_REQUEST = 'GET_KNOWLEDGE_DETAILS_REQUEST';
export const GET_KNOWLEDGE_DETAILS_SUCCESS = 'GET_KNOWLEDGE_DETAILS_SUCCESS';
export const GET_KNOWLEDGE_DETAILS_ERROR = 'GET_KNOWLEDGE_DETAILS_ERROR';
